apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - ../../base
  - acm-policy-appset.yaml
  - operator-acm-app.yaml

patches:
  - path: patch-operators-list.yaml
    target:
      kind: ApplicationSet
      name: cluster-operators-applicationset
