apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - acm-policy-appset.yaml

# patches:
#   - target:
#       name: cluster-config-app-of-apps
#       kind: Application
#     patch: |-
#       - op: replace
#         path: /spec/source/path
#         value: clusters/overlays/acm-hub
