- op: add
  path: /spec/generators/0/list/elements
  value:
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: operator-openshift-dev-spaces
        path: components/operators/openshift-dev-spaces
