apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: acm-config
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - 'https://github.com/rh-datascience-and-edge-practice/acm-hub-gitops.git'
